include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml
  # - template: Verify/Browser-Performance.gitlab-ci.yml

image: registry.gitlab.com/hmajid2301/pnpm-docker-ci:6faf9994486627a07ff45fa574f5c9e8df669413

stages:
  - test

.task:
  stage: test
  only:
    - merge_request
  before_script:
    - pnpm install

lint:
  extends: .task
  script:
    - task lint

format:check:
  extends: .task
  script:
    - task format:check

# browser_performance:
#   stage: test
#   only:
#     - merge_request
#   variables:
#     URL: https://deploy-preview-${CI_MERGE_REQUEST_IID}--bookmarkey.netlify.app
#   before_script:
#     - echo $URL > environment_url.txt
#     - echo $URL

check:
  extends: .task
  script:
    - cp .env.sample .env
    - task check

tests:unit:
  only:
    - merge_request
    - main
  extends: .task
  script:
    - task unit:tests
  artifacts:
    reports:
      junit: test-results/junit.xml

tests:e2e:
  image:
    name: registry.gitlab.com/hmajid2301/playwright-docker:25aca466f78e9d4f413e75cdb19fd9209c4fab10
    entrypoint: [""]
  services:
    - name: docker:dind
  variables:
    VITE_TEST_POCKET_BASE_URL: "http://docker:9090"
    VITE_POCKET_BASE_URL: "http://docker:9090"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  extends: .task
  script:
    - npx playwright install
    - task e2e:tests -- --reporter=junit
    - npx nyc report --report-dir ./coverage --temp-dir .nyc_output --reporter=cobertura --exclude-after-remap false
    - npx nyc report --report-dir ./coverage --temp-dir .nyc_output --reporter=text --exclude-after-remap false
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit: results.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    when: always
    paths:
      - test-results/
    expire_in: 1 week
