image: node:19.1.0

stages:
  - pre
  - test
  - publish

before_script:
  - npm install -g @go-task/cli
  - npm ci

lint:
  stage: test
  only:
    - merge_request
  script:
    - task lint

format:
  stage: test
  only:
    - merge_request
  script:
    - task format

test:unit:
  stage: test
  only:
    - merge_request
  script:
    - task unit_tests

check:
  stage: test
  only:
    - merge_request
  script:
    - task check
