include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

image: registry.gitlab.com/hmajid2301/pnpm-docker-ci:6faf9994486627a07ff45fa574f5c9e8df669413

stages:
  - test
  - deploy

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

.task:
  before_script:
    - pnpm install

lint:
  stage: test
  only:
    - merge_request
  extends: .task
  script:
    - task lint

format:
  stage: test
  only:
    - merge_request
  extends: .task
  script:
    - task format

coverage:unit:
  stage: test
  only:
    - merge_request
    - main
  extends: .task
  script:
    - time task coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit: test-results/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

tests:e2e:
  stage: test
  only:
    - merge_request
  image:
    name: registry.gitlab.com/hmajid2301/playwright-docker:bfb03856092c2fa9d0f4d3db97034e7aab78d727
    entrypoint: [""]
  services:
    - name: docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    VITE_POCKET_BASE_URL: "http://docker:9090"
  parallel: 2
  extends: .task
  script:
    - npx playwright install
    - echo "VITE_POCKET_BASE_URL='http://docker:9090'" >> .env.test
    - task e2e_tests -- --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL
  after_script:
    - cat svelte_playwright.log
  artifacts:
    when: always
    paths:
      - test-results/
    expire_in: 1 week

check:
  stage: test
  only:
    - merge_request
  extends: .task
  script:
    - task check
