include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml
  - template: Verify/Browser-Performance.gitlab-ci.yml

image: registry.gitlab.com/hmajid2301/pnpm-docker-ci:6faf9994486627a07ff45fa574f5c9e8df669413

stages:
  - test
  - deploy
  - notify

.task:
  stage: test
  only:
    - merge_request
  before_script:
    - pnpm install

lint:
  extends: .task
  script:
    - task lint

format:check:
  extends: .task
  script:
    - task format:check

browser_performance:
  only:
    - merge_requests
  variables:
    URL: https://deploy-preview-${CI_MERGE_REQUEST_IID}--bookmarkey.netlify.app

coverage:unit:
  only:
    - merge_request
    - main
  extends: .task
  script:
    - task coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit: test-results/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

tests:e2e:
  image:
    name: registry.gitlab.com/hmajid2301/playwright-docker:bfb03856092c2fa9d0f4d3db97034e7aab78d727
    entrypoint: [""]
  services:
    - name: docker:dind
  variables:
    VITE_TEST_POCKET_BASE_URL: "http://docker:9090"
    VITE_POCKET_BASE_URL: "http://docker:9090"
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  parallel: 2
  extends: .task
  allow_failure: true
  script:
    - npx playwright install
    - echo "VITE_TEST_POCKET_BASE_URL='http://docker:9090'" >> .env.test
    - task e2e:tests -- --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL
    - npx nyc report --report-dir ./coverage --temp-dir .nyc_output --reporter=cobertura --exclude-after-remap false
    - npx nyc report --report-dir ./coverage --temp-dir .nyc_output --reporter=text --exclude-after-remap false
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      # junit: test-results/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    when: always
    paths:
      - test-results/
    expire_in: 1 week

check:
  extends: .task
  script:
    - cp .env.sample .env
    - task check
