include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

image: node:19.1.0

stages:
  - pre
  - test
  - deploy

before_script:
  - npm install -g @go-task/cli
  - npm ci

lint:
  stage: test
  only:
    - merge_request
  script:
    - task lint

format:
  stage: test
  only:
    - merge_request
  script:
    - task format

test:unit:
  stage: test
  only:
    - merge_request
  script:
    - task unit_tests
  allow_failure: true

tests:e2e:
  stage: test
  only:
    - merge_request
  image: mcr.microsoft.com/playwright:v1.29.0-jammy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    VITE_POCKET_BASE_URL: 'http://docker:9090'
  script:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get update
    - apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
    - npx playwright install
    - task e2e_tests
  after_script:
    - cat a.txt
  artifacts:
    when: always
    paths:
      - test-results/
    expire_in: 1 week

check:
  stage: test
  only:
    - merge_request
  script:
    - task check
