services:
  api:
    image: registry.gitlab.com/bookmarkey/api:latest
    entrypoint: []
    command: ./bookmarkey serve --http=0.0.0.0:8080 --encryptionEnv=PB_ENCRYPTION_KEY
    ports:
      - "8080:8080"
    environment:
      PB_ENCRYPTION_KEY: CKMeo1mZuTs18DWHItd8qbYZMC7rLCBq
    volumes:
      - ./pb_data:/pb_data
      - /pb_public
