[build]
publish = "build"
command = "pnpm run build"

[context.production.environment]
VITE_POCKET_BASE_URL = "https://pocketbase.bookmarkey.app"
VITE_SENTRY_DSN = "https://0e98ab5b4a4546c68bfdb4a265be3cbc@o4504622675525632.ingest.sentry.io/4504622759149568"
VITE = "production"

[context.next.environment]

[context.deploy-preview]

[context.deploy-preview.environment]
VITE_POCKET_BASE_URL = "https://preview.pocketbase.bookmarkey.app"
VITE_SENTRY_DSN = "https://0e98ab5b4a4546c68bfdb4a265be3cbc@o4504622675525632.ingest.sentry.io/4504622759149568"
VITE = "deploy-preview"

[[plugins]]
package = "@sentry/netlify-build-plugin"

[plugins.inputs]
sentryOrg = "bookmarkey"
sentryProject = "gui"
sentryRepository = "Bookmarkey / gui"

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/assets/*"

[headers.values]
cache-control = '''
    max-age=31536000,
    immutable
    '''
