[build]
publish = "build"
command = "npm run build"

[context.production.environment]
VITE_POCKET_BASE_URL = "bookmarkey.fly.dev"

[context.next.environment]

[context.deploy-preview]

[context.deploy-preview.environment]
VITE_POCKET_BASE_URL = "bookmarkey.fly.dev"
