[build]
publish = "build"
command = "pnpm run build"

[context.production.environment]
VITE_POCKET_BASE_URL = "https://pocketbase.bookmarkey.app"
VITE_SENTRY_DSN = 'https://38be6117d9454303a80c3875e56eec02@o247056.ingest.sentry.io/4504394811113472'

[context.next.environment]

[context.deploy-preview]

[context.deploy-preview.environment]
VITE_POCKET_BASE_URL = "https://preview.pocketbase.bookmarkey.app"
VITE_SENTRY_DSN = "https://38be6117d9454303a80c3875e56eec02@o247056.ingest.sentry.io/4504394811113472"

[[plugins]]
package = "@sentry/netlify-build-plugin"

[plugins.inputs]
sentryOrg = "bookmarkey"
sentryProject = "gui"
sentryRepository = "Bookmarkey / gui"

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/assets/*"

[headers.values]
cache-control = '''
    max-age=31536000,
    immutable
    '''
