[build]
publish = "build"
command = "npm run build"

[context.production.environment]
NETLIFY = "true"
VITE_POCKET_BASE_URL = "https://bookmarkey.fly.dev"

[context.next.environment]

[context.deploy-preview]

[context.deploy-preview.environment]
NETLIFY = "true"
VITE_POCKET_BASE_URL = "https://bookmarkey.fly.dev"
