version: '3'

tasks:
  build:
    cmds:
      - npm run build
    env:
      NETLIFY: true

  start:
    cmds:
      - docker compose up --build -d
      - npm run dev -- --open

  lint:
    cmds:
      - npm run lint

  format:
    cmds:
      - npm run format

  unit_tests:
    cmds:
      - npm run test:unit

  check:
    cmds:
      - npm run check

  prepare:
    cmds:
      - npm run prepare
