version: '3'

tasks:
  start:
    cmds:
      - npm run dev -- --open

  lint:
    cmds:
      - npm run lint

  format:
    cmds:
      - npm run format

  unit_tests:
    cmds:
      - npm run test:unit

  check:
    cmds:
      - npm run check
