version: '3'

tasks:
  build:
    cmds:
      - npm run build
    env:
      NETLIFY: true

  start:
    cmds:
      - docker compose up --build -d
      - npm run dev -- --host --port 5173 --open

  lint:
    cmds:
      - npm run lint -- --fix

  format:
    cmds:
      - npm run format

  unit_tests:
    cmds:
      - npm run test:unit

  coverage:
    cmds:
      - npm run coverage

  e2e_tests:
    cmds:
      - docker compose -f docker-compose.yml -f tests/docker-compose.test.yml up  -d
      - npm run test
    env:
      VITE_POCKET_BASE_URL: 'http://localhost:9090'

  check:
    cmds:
      - npm run check

  prepare:
    cmds:
      - npm run prepare

  update_types:
    cmds:
      - npm run sync

  run_prod:
    cmds:
      - docker compose up --build -d
      - npm run build
      - npm run preview
