version: "3"

tasks:
  build:
    cmds:
      - pnpm run build

  start:
    cmds:
      - docker compose up --build -d
      - pnpm run dev --host --port 5173 --open

  lint:
    cmds:
      - pnpm run lint --fix

  format:
    cmds:
      - pnpm run format

  unit_tests:
    cmds:
      - pnpm run test:unit

  coverage:
    cmds:
      - pnpm run coverage

  e2e_tests:
    cmds:
      - docker compose -f tests/docker-compose.test.yml up  -d
      - pnpm run test {{.CLI_ARGS}}
    env:
      VITE_POCKET_BASE_URL: "http://localhost:9090"

  check:
    cmds:
      - pnpm run check

  prepare:
    cmds:
      - pnpm run prepare

  update_types:
    cmds:
      - pnpm run sync

  run_prod:
    cmds:
      - docker compose up --build -d
      - pnpm run build
      - pnpm run preview --host
